### ISSUE TITLE
[BUG]: Defective display of svg in Arc browser

### ISSUE THREAD

**Issue by Denisskas** [LelouchFR/skill-icons#234]
### Description of the bug

Starting on Arc browser (Windows 11): 1.17.0 version and latest (1.18.0)
![Arc_wf4SafIaEg](https://github.com/user-attachments/assets/53c49b7c-50d3-4d45-9cb1-7ead6e59a649)

### Steps To Reproduce

1.View icons in github on PC

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by LelouchFR** [comment]
I don't see any problem there... Could you provide a little more informations ?

**Comment by Denisskas** [comment]
@LelouchFR Sorry, I should have done a comparison right away from different browsers.

Normal display of icons (Google Chrome)
![chrome_wWPSv6ttoC](https://github.com/user-attachments/assets/3e7e5c4a-8fcf-4d6b-a59b-381f2c74ee01)
Defective icon display of icons (Arc browser)
![Arc_V668fPYdAG](https://github.com/user-attachments/assets/8493ea52-014c-4cc4-8e1b-ceddb7332b05)

**Comment by LelouchFR** [comment]
@Denisskas By seeing this, I think more that the problem comes from the implementation that arc has done from the chromium browser (or how arc has been compiled from your side) which has changed something from the rendering from svg. Since the code does not change at any problem (svg whise). Maybe try finding info around other arc browser users, because I find that strange...

**Comment by LelouchFR** [comment]
I guess you can open an issue about it [here](https://resources.arc.net/hc/en-us/requests/new) and give us some updates about it (you can also share the gh issue). I'm going to close the issue since I don't think that problem comes from the side of the api, but you can still write here so we get update about the issue
