### ISSUE TITLE
[NEW ICON]: Wireshark

### ISSUE THREAD

**Issue by avirgos** [LelouchFR/skill-icons#246]
### Skill Name

Wireshark

### Why?

Popular tool used for network frame analysis.

### Reference Image

![wireshark](https://github.com/user-attachments/assets/cb9d7d0f-1eb9-48f6-9712-f9edd790826b)

### Svg Availability

- [X] I have given the official svg version of the logo in the Reference Image field.

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by paulemacedo** [comment]
waiting

**Comment by LelouchFR** [comment]
I'm sorry @paulemacedo, @avirgos that it takes so much time for this icon... The thing is that, **it's composed out of strokes**, which **on rescale**, it's **not going to change properties as wished**. So basically having to **make the whole icon from scratch** because of this, and it has to also have a harmony with other existing icons. I'm trying my best to make the best icons possible, but it can get pretty hard, not gonna lie.

**Comment by paulemacedo** [comment]
https://icon-sets.iconify.design/simple-icons/wireshark/

**Comment by LelouchFR** [comment]
@paulemacedo do you think that this could be okay ?

![image](https://github.com/user-attachments/assets/d26fe9dc-4e3e-4868-8672-6bdbb5381c87)

**Comment by paulemacedo** [comment]
sure, its nice 🥇 😄
